/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DailyValidateImport } from './routes/daily/validate'
import { Route as DailyLoginImport } from './routes/daily/login'
import { Route as DailySidebarImport } from './routes/daily/_sidebar'
import { Route as DailySidebarUserIndexImport } from './routes/daily/_sidebar/user/index'
import { Route as DailySidebarAccountIndexImport } from './routes/daily/_sidebar/account/index'
import { Route as DailySidebarAccountAccountImport } from './routes/daily/_sidebar/account/$account'

// Create Virtual Routes

const DailyImport = createFileRoute('/daily')()

// Create/Update Routes

const DailyRoute = DailyImport.update({
  path: '/daily',
  getParentRoute: () => rootRoute,
} as any)

const DailyValidateRoute = DailyValidateImport.update({
  path: '/validate',
  getParentRoute: () => DailyRoute,
} as any)

const DailyLoginRoute = DailyLoginImport.update({
  path: '/login',
  getParentRoute: () => DailyRoute,
} as any)

const DailySidebarRoute = DailySidebarImport.update({
  id: '/_sidebar',
  getParentRoute: () => DailyRoute,
} as any)

const DailySidebarUserIndexRoute = DailySidebarUserIndexImport.update({
  path: '/user/',
  getParentRoute: () => DailySidebarRoute,
} as any)

const DailySidebarAccountIndexRoute = DailySidebarAccountIndexImport.update({
  path: '/account/',
  getParentRoute: () => DailySidebarRoute,
} as any)

const DailySidebarAccountAccountRoute = DailySidebarAccountAccountImport.update(
  {
    path: '/account/$account',
    getParentRoute: () => DailySidebarRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/daily': {
      preLoaderRoute: typeof DailyImport
      parentRoute: typeof rootRoute
    }
    '/daily/_sidebar': {
      preLoaderRoute: typeof DailySidebarImport
      parentRoute: typeof DailyRoute
    }
    '/daily/login': {
      preLoaderRoute: typeof DailyLoginImport
      parentRoute: typeof DailyImport
    }
    '/daily/validate': {
      preLoaderRoute: typeof DailyValidateImport
      parentRoute: typeof DailyImport
    }
    '/daily/_sidebar/account/$account': {
      preLoaderRoute: typeof DailySidebarAccountAccountImport
      parentRoute: typeof DailySidebarImport
    }
    '/daily/_sidebar/account/': {
      preLoaderRoute: typeof DailySidebarAccountIndexImport
      parentRoute: typeof DailySidebarImport
    }
    '/daily/_sidebar/user/': {
      preLoaderRoute: typeof DailySidebarUserIndexImport
      parentRoute: typeof DailySidebarImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  DailyRoute.addChildren([
    DailySidebarRoute.addChildren([
      DailySidebarAccountAccountRoute,
      DailySidebarAccountIndexRoute,
      DailySidebarUserIndexRoute,
    ]),
    DailyLoginRoute,
    DailyValidateRoute,
  ]),
])

/* prettier-ignore-end */
